### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by gradel**
well, just german translation

### CODE REVIEW

**Comment by rockymeza** [comment]
Cool! I'll take a look over the weekend.

-rocky
2016年3月29日 下午8:14於 "gradel" <notifications@github.com>寫道：

**Comment by rockymeza** [comment]
This is great! I'm so excited. Thank you for putting in the time to do this! I just have some questions before we merge this.

Super fun!
image

I don't know German, but it sure looks like German to me!

I have a question, is title *title* or *titel*?
image

Also it seems like Pages is *Seiten*, but that seems to clash with Sites, which also shows up as *Seiten*.
image
Is there any way we can work around this? I'm worried about confusing people.

P.s. the tests failures are unrelated -- have been fixed in master

**Comment by gradel** [comment]
Thx a lot for reviewing!

"title" and some other stuff are translated now, have overlooked these.

In german there exists only one word for site and page: Seite. This is a constant source of confusion, but there is no proper solution to it. The best variant, I think, would be to translate site with Site, since this english word is widely used in german too, but this is already handled by mezzanine.
I think we can go with it, since the the editors will not have the permission to handle sites, so they will not see this entry and the admin knows about the ambiguity.

**Comment by rockymeza** [comment]
Hi @gradel,

Thanks so much for this! I have merged it for now. There was an issue that I found with some of the CSS (see #369), but I figured it would be more helpful to merge this now and fix it later.

I'll see if we can't get a release soon.

Thanks again!

**Pull request merged**
