### PR TITLE
new travis with pip caching

### PR DESCRIPTION
**Pull request by gavinwahl**
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

### CODE REVIEW

**Comment by rockymeza** [comment]
https://github.com/fusionbox/django-widgy/blob/master/.travis.yml#L4-L6

Does cover it for us?

**Comment by gavinwahl** [comment]
It'd be nice to use wheels to avoid recompiling stuff http://www.ptone.com/dablog/2013/07/can-you-wheel-the-love/

**Comment by acatton** [comment]
It looks like it's already fixed on master.

**Comment by gavinwahl** [comment]
There are wheels?

**Pull request closed without merging**
