### PR TITLE
Allow HTML in help_text for widgets

### PR DESCRIPTION
**Pull request by rockymeza**
Django does this as well.

### CODE REVIEW

**Comment by gavinwahl** [comment]
> Django does this as well.

Really? Since when?

**Comment by rockymeza** [comment]
Example of HTML in help_text: https://github.com/django/django/blob/master/django/contrib/auth/forms.py#L99-L103

I tried to trace that back through the history, and it was introduced in https://github.com/django/django/commit/718a5ba1a1a77374c26b134ded46dab13776d1a1 (by Adrian Holovaty), in 2011, so, I'm thinking, that at least since 2011.

Upon further inspection, it seems that HTML in help_text was supported since help_text was introduced in https://github.com/django/django/commit/cf75fcc8321b822cb4758d167f1fade56a60ad4f (also by Adrian Holovaty) in 2007.

**Comment by rockymeza** [comment]
To be fair, I don't know if it's documented, I only learned about when we were working on authtools.

**Comment by gavinwahl** [comment]
It's documented <https://docs.djangoproject.com/en/1.7/ref/models/fields/#help-text>

**Pull request merged**
