### PR TITLE
Django 1.8 Support

### PR DESCRIPTION
**Pull request by gavinwahl**
- get_fields_with_model no longer does what LinkField needs it to. See https://github.com/pipermerriam/django-widgy/commit/19d4c4ad902e61848ee5e1619756109526ee311f#diff-3b25c7f883ce7e1bab6fd27789267adcR1 and https://code.djangoproject.com/ticket/24231
- The Model._meta.module_name alias is removed.
- The Model._meta.get_(add|change|delete)_permission methods are removed.
- django.forms.widgets.RadioInput is removed.
- The module django.test.simple and the class django.test.simple.DjangoTestSuiteRunner are removed.
- The backward compatible shims introduced to rename get_query_set and similar queryset methods are removed. This affects the following classes: BaseModelAdmin, ChangeList, BaseCommentNode, GenericForeignKey, Manager, SingleRelatedObjectDescriptor and ReverseSingleRelatedObjectDescriptor.

### CODE REVIEW

**Comment by gavinwahl** [comment]
This is done except for contrib. You need to install mezzanine, mptt, and filer from source to work on 1.8.

**Comment by rockymeza** [comment]
Should we wait on those releases before merging the 1.8 branch? Or can we
merge now and not wait to release? Or should we merge and release and just
add release notes stating that you need to install those packages from
source?

I think we should just wait for a little bit.
*Rocky Meza*, Programmer
fusionbox*▝*
o: 303.952.7490

www.fusionbox.com
<http://www.fusionbox.com/?utm_source=fb%2Bemail&utm_medium=email&utm_campaign=email%2Btracking>

This information is confidential and intended solely for the use
of the individual or entity to whom it is addressed. If you have
received this email in error please notify the sender.

**Comment by rockymeza** [comment]
django-extensions is [deprecating](https://django-extensions.readthedocs.org/en/latest/field_extensions.html) their UUIDField because Django 1.8 adds one.

It would be nice to use the built-in UUIDField for Django 1.8 and fill it in with django-extensions for <1.8.

**Comment by gavinwahl** [comment]
mptt and polymorphic have been released. Just waiting on mezzanine.

**Comment by gavinwahl** [comment]
We should fix the check warnings:

```
widgy.VersionTracker.head: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
widgy.VersionTracker.working_copy: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
```

We can just change it to a OneToOneField unless someone is using the reverse relationship (I don't think we are anywhere).

**Comment by acatton** [comment]
Addressed in #326

**Pull request closed without merging**
