### PR TITLE
Moved many dependencies to extras_require

### LINKED ISSUE #218: Trimmed requirements for those who don't use Mezzanine
I wanted to investigate building Widgy into my CMS so I pip installed it. 

After a lot of churning I ended up with: mezzanine django-treebeard django-filer django-polymorphic PyScss markdown bleach beautifulsoup4 html2text phonenumbers django-argonauts filebrowser-safe grappelli-safe tzlocal requests requests-oauthlib future easy-thumbnails django-mptt html5lib pytz oauthlib

I definitely don't want Mezzanine or Grappelli - I have my own CMS and my own admin skin. I also have my own fork of Django filebrowser. A lot of the other requirements seem rather orthogonal to Widgy's stated intent but it's not clear which can be safely removed.

### PR DESCRIPTION
**Pull request by rockymeza**
This is an attempt to resolve #218.

It's not ready to merge, as I didn't really know what to do about the site option for Callout.  I did something silly for now.  I created a minimalistic install of widgy[0] in order to test this out.  I wasn't sure how to go about doing it otherwise.  It has a couple of branches for the different dependency groups.

I also removed the dependency on South.

[0]: https://github.com/fusionbox/widgy-bare

### CODE REVIEW

**Comment by pipermerriam** [comment]
I'm looking at taking over this PR.  One of the things that it seems needs to change is to alter the testing matrix.  Would you guys be amenable to modifying the `.travis.yml` and `tox.ini` to follow the pattern found in https://github.com/pipermerriam/flex/blob/master/.travis.yml and the corresponding `tox.ini`

Essentially, rather than duplicating the tox environments in the `.travis.yml` you just delegate out to tox to run a specific tox environment.

**Comment by gavinwahl** [comment]
I don't think anyone is actually using tox. I'd rather just remove tox.ini

**Comment by pipermerriam** [comment]
How do you run tests against different versions then?

**Comment by rockymeza** [comment]
I have lots of projects that use widgy, so I just test in those projects
virtualenvs, and then use Travis to run against different Pythons.

-Rocky Meza
2015年1月10日 上午2:41于 "Piper Merriam" <notifications@github.com>写道：

**Comment by pipermerriam** [comment]
Couple of benefits to this method.

- Easy to test across not just different pythons, but different django version, etc.
- You can still run tests locally exactly the same way using `make tests`
- Testing with `tox` has the added benefit of not being subject to certain kinds of test failures (forgetting to include a dependency and only finding out once travis runs and blows up on an `ImportError`).
- Easier to configure `travis` since travis is just a proxy for `tox`.  I know I have personally spent too long *futzing* with travis to get my configuration correct.
- Increases the similarity of your local test environment and the environment on Travis.

I will change it back if this change is unwanted.

**Comment by acatton** [comment]
Let's just move the discussion to #294.

**Pull request closed without merging**
